"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../lib/supabase";
import BookingModal from "../components/BookingModal";
import html2canvas from "html2canvas";

const STATUS={booked:"จองแล้ว",waiting_payment:"รอชำระเงิน",maintenance:"ปิดปรับปรุง",cancelled:"ยกเลิก"};
const thaiMonths=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
const thaiWeek=["อา.","จ.","อ.","พ.","พฤ.","ศ.","ส."];
const META_PREFIX="__SC_META__", META_NOTE="__SC_NOTE__", META_FOOD="__SC_DATA__";
function pad(n){return String(n).padStart(2,"0")}
function dateKey(y,m,d){return `${y}-${pad(m+1)}-${pad(d)}`}
function isValidDateKey(key){return typeof key==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(key)&&!Number.isNaN(new Date(key+"T00:00:00").getTime())}
function addDays(key,n){if(!isValidDateKey(key))return "";const d=new Date(key+"T00:00:00");d.setDate(d.getDate()+Number(n||0));return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)}
function getThaiToday(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const v={};p.forEach(x=>{if(x.type!=="literal")v[x.type]=x.value});return `${v.year}-${v.month}-${v.day}`}
function legacyFoodItems(value){const raw=String(value||"");if(!raw||raw==="ไม่ได้สั่งเพิ่ม")return [];return raw.split(/\s*,\s*/).map(part=>{const m=part.match(/^(.+?)\s+([\d,]+)\s*บาท$/);return m?{name:m[1].trim(),price:Number(m[2].replace(/,/g,""))}:null}).filter(Boolean)}
function parseFoodData(value){const raw=String(value||"");if(!raw.startsWith(META_FOOD))return {meta:{},legacy:legacyFoodItems(value)};try{const meta=JSON.parse(raw.slice(META_FOOD.length).trim());return {meta:meta||{},legacy:Array.isArray(meta?.food_items)?meta.food_items:[]}}catch{return {meta:{},legacy:[]}}}
function parseBooking(b){const raw=String(b.note||"");const fd=parseFoodData(b.food);if(!raw.startsWith(META_PREFIX)){const meta=fd.meta||{};return {...b,...meta,check_in:meta.check_in||b.booking_date,check_out:meta.check_out||addDays(meta.check_in||b.booking_date,1),booking_type:meta.booking_type||"room",food_items:Array.isArray(meta.food_items)?meta.food_items:(fd.legacy.length?fd.legacy:legacyFoodItems(b.food)),extra_items:Array.isArray(meta.extra_items)?meta.extra_items:[],note:raw};}const body=raw.slice(META_PREFIX.length),idx=body.indexOf(META_NOTE);if(idx<0)return {...b,...fd.meta,check_in:fd.meta?.check_in||b.booking_date,check_out:fd.meta?.check_out||addDays(fd.meta?.check_in||b.booking_date,1),booking_type:fd.meta?.booking_type||"room",food_items:Array.isArray(fd.meta?.food_items)?fd.meta.food_items:(fd.legacy.length?fd.legacy:legacyFoodItems(b.food)),extra_items:Array.isArray(fd.meta?.extra_items)?fd.meta.extra_items:[],note:raw};try{const meta=JSON.parse(body.slice(0,idx).trim());return {...b,...meta,check_in:meta.check_in||fd.meta?.check_in||b.booking_date,check_out:meta.check_out||fd.meta?.check_out||addDays(meta.check_in||fd.meta?.check_in||b.booking_date,1),booking_type:meta.booking_type||fd.meta?.booking_type||"room",food_items:Array.isArray(meta.food_items)?meta.food_items:(fd.legacy.length?fd.legacy:legacyFoodItems(b.food)),extra_items:Array.isArray(meta.extra_items)?meta.extra_items:(Array.isArray(fd.meta?.extra_items)?fd.meta.extra_items:[]),note:body.slice(idx+META_NOTE.length).trim()}}catch{return {...b,...fd.meta,check_in:fd.meta?.check_in||b.booking_date,check_out:fd.meta?.check_out||addDays(fd.meta?.check_in||b.booking_date,1),booking_type:fd.meta?.booking_type||"room",food_items:fd.legacy.length?fd.legacy:legacyFoodItems(b.food),extra_items:Array.isArray(fd.meta?.extra_items)?fd.meta.extra_items:[],note:raw}}}
function inStay(b,key){const start=b.check_in||b.booking_date,end=b.check_out||addDays(start,1);return isValidDateKey(start)&&isValidDateKey(end)&&start<=key&&key<end}

export default function Home(){
 const [today,setToday]=useState(getThaiToday());
 const [viewDate,setViewDate]=useState(()=>{const t=new Date(getThaiToday()+"T00:00:00");return new Date(t.getFullYear(),t.getMonth(),1)});
 const [bookings,setBookings]=useState([]),[selectedDate,setSelectedDate]=useState(null),[selectedBooking,setSelectedBooking]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[monthPicker,setMonthPicker]=useState(false); const calendarRef=useRef(null);
 async function loadBookings(){
  setLoading(true);setError("");
  const start=new Date(viewDate.getFullYear(),viewDate.getMonth(),1); const end=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0);
  const from=addDays(dateKey(start.getFullYear(),start.getMonth(),start.getDate()),-62); const to=addDays(dateKey(end.getFullYear(),end.getMonth(),end.getDate()),1);
  const {data,error}=await supabase.from("bookings").select("*").gte("booking_date",from).lte("booking_date",to).order("created_at",{ascending:false});
  if(error){setError(error.message);setBookings([])}else setBookings((data||[]).map(parseBooking)); setLoading(false);
 }
 useEffect(()=>{loadBookings()},[viewDate]);
 useEffect(()=>{const c=supabase.channel("bookings-live").on("postgres_changes",{event:"*",schema:"public",table:"bookings"},loadBookings).subscribe();return()=>supabase.removeChannel(c)},[viewDate]);
 useEffect(()=>{const t=setInterval(()=>setToday(getThaiToday()),30000);return()=>clearInterval(t)},[]);
 const days=useMemo(()=>{const y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();const a=[];for(let i=0;i<first;i++)a.push(null);for(let d=1;d<=count;d++)a.push(d);return a},[viewDate]);
 const byDate=useMemo(()=>{const map={};for(const b of bookings){if(b.status==="cancelled")continue;const start=b.check_in||b.booking_date,end=b.check_out||addDays(start,1);let d=new Date(start+"T00:00:00"),last=new Date(end+"T00:00:00");while(d<last){const k=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;(map[k] ||= []).push(b);d.setDate(d.getDate()+1)}}return map},[bookings]);
 function openDay(d){if(!d)return;const k=dateKey(viewDate.getFullYear(),viewDate.getMonth(),d);const active=(byDate[k]||[])[0];if(active)setSelectedBooking(active);else setSelectedDate(k)}
 function moveMonth(n){setViewDate(new Date(viewDate.getFullYear(),viewDate.getMonth()+n,1));setMonthPicker(false)}
 function chooseMonth(m){setViewDate(new Date(viewDate.getFullYear(),m,1));setMonthPicker(false)}
 async function shareOrDownload(blob,fileName){if(!blob)return;const file=new File([blob],fileName,{type:"image/png"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:"บันทึกปฏิทิน"});return}catch(e){if(e?.name==="AbortError")return}}const a=document.createElement("a");a.download=fileName;a.href=URL.createObjectURL(blob);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function downloadCalendar(){if(!calendarRef.current)return;const canvas=await html2canvas(calendarRef.current,{backgroundColor:"#fff",scale:Math.min(2,Math.max(1.5,window.devicePixelRatio||1.5)),useCORS:true,onclone:doc=>{const root=doc.querySelector("[data-calendar-export]");if(!root)return;root.querySelectorAll(".circle-btn,.chev,.calendar-download-row,.loading,.error,.mini-status,.month-picker,.menu-btn,.brand-icon,.brand h1").forEach(el=>el.style.display="none");const title=root.querySelector(".month-title");if(title){title.style.cursor="default";title.style.fontSize="32px";title.style.fontWeight="800";title.style.color="#000";title.style.padding="0";title.style.margin="0"}root.querySelectorAll(".day strong").forEach(el=>{el.style.color="#000";el.style.background="transparent";el.style.width="auto";el.style.height="auto";el.style.display="block"});root.style.padding="12px";root.style.background="#fff"}});const blob=await new Promise(r=>canvas.toBlob(r,"image/png"));await shareOrDownload(blob,`ปฏิทิน-${thaiMonths[viewDate.getMonth()]}-${viewDate.getFullYear()+543}.png`)}
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-icon">✓</div><h1>ปฏิทินฝ่ายขาย</h1></div><button className="menu-btn" aria-label="เมนู"><span></span><span></span><span></span></button></header><section ref={calendarRef} data-calendar-export className="calendar-section"><div className="month-row"><button className="circle-btn" onClick={()=>moveMonth(-1)}>‹</button><div className="month-picker-wrap"><button className="month-title" onClick={()=>setMonthPicker(v=>!v)}>{thaiMonths[viewDate.getMonth()]} {viewDate.getFullYear()+543} <span className="chev">⌄</span></button>{monthPicker&&<div className="month-picker">{thaiMonths.map((n,i)=><button key={n} className={i===viewDate.getMonth()?"selected":""} onClick={()=>chooseMonth(i)}>{n}</button>)}</div>}</div><button className="circle-btn" onClick={()=>moveMonth(1)}>›</button></div><div className="week-row">{thaiWeek.map(x=><div key={x}>{x}</div>)}</div>{error&&<div className="error">เชื่อมต่อฐานข้อมูลไม่ได้: {error}</div>}<div className="calendar-grid">{days.map((d,i)=>{if(!d)return <div className="day empty" key={`e-${i}`}/>;const key=dateKey(viewDate.getFullYear(),viewDate.getMonth(),d),active=(byDate[key]||[])[0],status=active?.status,isToday=key===today;return <button className={`day ${status?`status-${status}`:""} ${isToday?"today":""}`} key={key} onClick={()=>openDay(d)}><strong>{d}</strong>{active&&<span className="mini-status">{STATUS[status]}</span>}</button>})}</div>{loading&&<div className="loading">กำลังโหลดข้อมูล…</div>}<div className="calendar-download-row export-hide"><button className="btn secondary" onClick={downloadCalendar}>ดาวน์โหลดรูปภาพหน้าปฏิทิน</button></div></section><BookingModal date={selectedDate} booking={selectedBooking} onClose={()=>{setSelectedDate(null);setSelectedBooking(null)}} onSaved={(savedDate)=>{setSelectedDate(null);setSelectedBooking(null);if(savedDate&&isValidDateKey(savedDate)){const d=new Date(savedDate+"T00:00:00");setViewDate(new Date(d.getFullYear(),d.getMonth(),1));}else loadBookings()}}/></main>
}
